task 1 edited

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,30 +1,25 @@
 #!/usr/bin/env bash
 # installs nginx and starts a remote server
 
+# Check if running as root
+if [[ $EUID -ne 0 ]]; then
+   echo "This script must be run as root"
+   exit 1
+fi
 
-echo -e "Updating and installing Nginx.\n"
-sudo apt-get update -y -qq && \
-	 sudo apt-get install nginx -y
+apt-get -y update
+apt-get -y install nginx
+ufw allow 'Nginx HTTP'
 
-echo -e "\nSetting up some minor stuff.\n"
+# Check if the file exists before copying
+if [ -f "/var/www/html/index.nginx.debian.html" ]; then
+    cp /var/www/html/index.nginx.debian.html /var/www/html/index/debian.html.bckp
+else
+    echo "Error: index.nginx.debian.html not found. Creating a new file."
+fi
 
-# starting nginx service
-sudo service nginx start
+# Create a new index file with "Hello World!"
+echo 'Hello World!' > /var/www/html/index.nginx-debian.html
 
-# allowing nginx on firewall
-sudo ufw allow 'Nginx HTTP'
-
-# Give the user ownership to website files for easy editing
-sudo chown -R "$USER":"$USER" /var/www/html
-sudo chmod -R 755 /var/www
-
-# Backup default index
-cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
-
-# Creating new index
-echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
-
-# Restarting nginx
-sudo service nginx restart
-
-echo -e "\nCompleted. ✅\n"
+# Restart nginx service
+service nginx restart
